FROM ibmcom/ibmnode

ENV NODE_ENV production
ENV PORT 8080

WORKDIR "/app"

# Install app dependencies
COPY package.json package-lock.json ./app/
RUN cd /app; npm install

# Bundle app source
COPY . /app

EXPOSE 8080

CMD ["/bin/bash"]

ARG bx_dev_user=root
ARG bx_dev_userid=1000
RUN BX_DEV_USER=$bx_dev_user
RUN BX_DEV_USERID=$bx_dev_userid
RUN if [ $bx_dev_user != "root" ]; then useradd -ms /bin/bash -u $bx_dev_userid $bx_dev_user; fi
